- .travis.yml
- CHANGELOG.md
- src/lib.rs
This should allow the crate to work with older rusts (at least back to 1.15.1, as required)
> Work with older rust versions

- Cargo.toml
This crate has promised Rust 1.13.0 in its 0.2.x series so don't break that.
> pin versions to not break compat

- examples/clap.rs
- examples/large-example/src/main.rs
- examples/structopt.rs
- examples/timestamp.rs
- src/lib.rs
Also `Timestamp::Microsecond` should be represented by "us".
> Add millisecond timestamp resolution

- src/lib.rs
- tests/no_levels_output.rs
You can say `.levels(false)` to disable log level prefixes in the messages. (The current behavior, that of levels being printed, is preserved as the default.)
This can be useful e. g. in command-line utilities where you usually just want messages to appear on stderr, without the "log levels" (which are an implementation detail arising from the choice to use `log` instead of `if` + `eprintln!`).
> Add an option to disable printing message level

- Cargo.toml
I'm trying to test my crate for compatibility with `-Z minimal-versions`, and `stderrlog` pulls in seriously outdated pre-Rust-1.0 transitive dependencies.
> -Z minimal-versions

- src/lib.rs
Doc comment accidentally says it influences. timestamps.
> Fix docs for show_level()

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/large-example/Cargo.toml
- src/lib.rs
What started as a wish to fix #20 ended up as a larger deps and MSRV update (#22), plus fixing some bitrot. Nothing too scary, but the MSRV bump does imply a semver bump.
Rust 1.16 was 11 months old when it was chosen as the MSRV. The new MSRV (rust 1.32) is 16 months old and brings rust edition 2018, so it should have wide adoption at this stage.
I kept an eye on build/test/bench using both the MSRV and nightly compiler, as well as minimal dep versions. In the CI, I use minimal-versions with nightly only because I don't know whether `cargo +nightly update -Z minimal-version`  would succeed when `$TRAVIS_RUST_VERSION = 1.32.0`. If that's supported, it would be a better CI setup.
Thanks for the review.
> Update deps and msrv

- src/lib.rs
This is helpful when `stderrlog` is used in a binary that is part of a cargo workspace with multiple crates. It is necessary in such cases to know which crate a certain log message is coming from.
> Added support for showing module names in log output

- Cargo.toml
- src/lib.rs
- tests/utils/mod.rs
CachedThreadLocal have been deprecated in 1.1.0, see: https://docs.rs/thread_local/latest/thread_local/struct.CachedThreadLocal.html
ONCE_INIT deprecation notice here: https://doc.rust-lang.org/std/sync/constant.ONCE_INIT.html
> update thread_local from ~1.0 to ~1.1 and fix deprecation warnings

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- src/lib.rs
In 4ffd89856 the build is broken due to thread_local pulling in a
version of once_cell that doesn't work with the MSRV.
> attempt to fix build broken by 4ffd89856

- src/lib.rs
- tests/debug_level_log.rs
- tests/error_level.rs
- tests/info_level.rs
- tests/quiet_trace_level.rs
Allow users to specify the verbosity with the levels from the log crate as well as the numerical values used today. Document the numerical values used today as well. fixes #28. fixes #32.
> document verbosity and allow it to be specified differently

- Cargo.toml
Ref: https://salsa.debian.org/rust-team/debcargo-conf/-/commit/a64c5d1a365974e0b64c5b386799deed7e6c28fe
> update docopt from ~1.0 to ~1.1 and structopt from 0.2.11 to 0.3.20

- CHANGELOG.md
- src/lib.rs
The `show_module_names` field was missing from the manual `Debug` implementation for `StdErrLog`.
> Add missing field to `StdErrLog` debug implementation

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
The timestamps feature of `stderrlog` relies upon the `chrono` crate, which:
(a) means pulling in an additional 5 dependencies,
(b) has had CVE related issues of late (eg #31).
Now, a new crate feature `timestamps` has been added, which is enabled by default, but can be switched off using `default-features = false` should consumers of `stderrlog` not use timestamps and want to reduce the size of the dependency tree + security scan false positives.
> Support disabling the timestamps feature

- Cargo.lock.msrv
- Cargo.toml
The "oldtime" feature of the chrono crate depends on a version of the time crate affected by RUSTSEC-2020-0071.
It does not appear that stderrlog depends on functionality provided by this feature.
> Disable "oldtime" feature of chrono

- Cargo.lock.msrv
- Cargo.toml
- examples/clap.rs
- examples/timestamp.rs
- src/lib.rs
I know clap 4 is out, but clap 3 is the version that is currently packaged in Debian sid, and it's still an improvement to go from 2 -> 3 I think.
> upgrade the dev dependency clap from 2.33 to 3

- examples/large-example/src/main.rs
- src/lib.rs
Fixed the module filtering example to actually work. Added extra tests going forward. fixes #27
> fixed module filtering example and add tests

- .github/workflows/ci.yml
- src/lib.rs
This used the actions-rs org's GitHub Actions which are all retired and unmaintained. Rewrote the whole flow to collapse down to as minimal number of jobs as possible and tried to just use the native Rust bits.
> ci: updates because many steps are retired

- src/lib.rs
- tests/pty_closed.rs
This adds a test to check the behavior when logging after a pty closes and removes the unwanted panics.
> Do not panic when pty closes

- src/lib.rs
This is #52 just pushed correctly.
> Only style the level label
